apiVersion: v1
kind: ConfigMap
metadata:
  name: dbsecrets
  namespace: testkits
data:
  username: "root"
  password: "tiJ7FlBv694NBv35"
  ip: "10.70.192.5"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redissecrets
  namespace: testkits
data:
  hostname: "redis-13195.c252.ap-southeast-1-1.ec2.cloud.redislabs.com"
  password: "raspberrypi"
  port: "13195"