---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-phpmyadmin
  namespace: testkits
  labels:
    app: {{ .Release.Name }}-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-phpmyadmin
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-phpmyadmin
    spec:
      containers:
        - name: {{ .Release.Name }}-phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: {{ .Release.Name }}-mysql-service.testkits.svc.cluster.local
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: dbsecrets
                  key: password
            - name: PMA_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-phpmyadmin-internal"
spec:
  type: NodePort
  selector:
    app: "{{ .Release.Name }}-phpmyadmin"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-phpmyadmin-ingress"
spec:
  rules:
    - host: "phpmyadmin.{{.Values.id}}.{{.Values.domain}}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-phpmyadmin-internal"
                port:
                  number: 80
  ingressClassName: nginx
